### ISSUE TITLE
i did what you requested but i still have errors in " sbt assemly" 

### ISSUE THREAD

**Issue by arezki1990** [stefanobaghino/spark-twitter-stream-example#4] opened 2016-12-08 11:52 UTC
at java.lang.Thread.run(Thread.java:745)
[error] (*:assembly) java.util.zip.ZipException: duplicate entry: META-INF/MANIFEST.MF
[error] Total time: 82 s, completed Dec 8, 2016 12:35:02 PM

**Comment by stefanobaghino** [comment] 2016-12-08 12:49
I don't know why it didn't happen in my tests yesterday but the issue is that I keep the first `MANIFEST.MF` in the classpath and then add the one from my assembly. Fixing it right now, thanks for reporting.

**Comment by stefanobaghino** [comment] 2016-12-08 13:15
Fixed by #5

**Closed** 2016-12-08 13:16 UTC
